# permissions for end users to edit appdeploys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: appdeploy-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: app-deploy-operator
    app.kubernetes.io/part-of: app-deploy-operator
    app.kubernetes.io/managed-by: kustomize
  name: appdeploy-editor-role
rules:
- apiGroups:
  - akoserwal.akoserwal
  resources:
  - appdeploys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - akoserwal.akoserwal
  resources:
  - appdeploys/status
  verbs:
  - get
