# permissions for end users to view appsdeployers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: appsdeployer-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: app-deploy-operator
    app.kubernetes.io/part-of: app-deploy-operator
    app.kubernetes.io/managed-by: kustomize
  name: appsdeployer-viewer-role
rules:
- apiGroups:
  - apps.akoserwal
  resources:
  - appsdeployers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.akoserwal
  resources:
  - appsdeployers/status
  verbs:
  - get
