---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.akoserwal
  resources:
  - appsdeployers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.akoserwal
  resources:
  - appsdeployers/finalizers
  verbs:
  - update
- apiGroups:
  - apps.akoserwal
  resources:
  - appsdeployers/status
  verbs:
  - get
  - patch
  - update
